openapi: 3.0.0
info:
  title: User Microservices (Adi Bangkit)
  version: 1.0.0
servers:
  - url: http://localhost:5001
    variables:
      base_url:
        default: https://localhost:5001
        description: local
tags:
  - name: User

paths:
  /user/register:
    post:
      tags:
        - User
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                password:
                  type: string
                fullname:
                  type: string
              example:
                email: string
                password: string
                name: string
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    token: string
                  error_message: ""

        "409":
          description: Failed response
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  data: []
                  error_message: "string"
  /user/login:
    post:
      tags:
        - User
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: string
                password: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    token: string
                  error_message: string

components:
  schemas:
    Ping:
      properties:
        success:
          type: boolean
        status:
          type: number
        message:
          type: string
      example:
        success: true
        status: 200
        message: "Ticket Reservation API"

    Error:
      properties:
        success:
          type: boolean
        status:
          type: boolean
        error_message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  responses:
    Unauthorized:
      description: Unauthorized response
      content:
        application/json:
          schema:
            properties:
              success:
                type: boolean
              message:
                type: string
            example:
              success: false
              message: "invalid signature"
    Forbidden:
      description: Forbidden response
      content:
        application/json:
          schema:
            properties:
              success:
                type: boolean
              message:
                type: string
            example:
              success: false
              message: "You are not allowed"
